import { Montserrat, Baloo_2, Shippori_Mincho } from "next/font/google";
import "./globals.css";

const baloo_2 = Baloo_2({
  variable: "--font-baloo_2",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const shippori_mincho = Shippori_Mincho({
  variable: "--font-shippori_mincho",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${baloo_2.variable} ${shippori_mincho.variable} antialiased bg-[#0e1618]`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}



