import { Montserrat, Baloo_2 } from "next/font/google";
import "./globals.css";
import AppProvider from "@/src/components/common/app-provider";
import { Toaster } from "@/src/components/ui/sonner";

const baloo_2 = Baloo_2({
  variable: "--font-baloo_2",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${baloo_2.variable}  antialiased bg-[#0e1618]`}
      >
        <AppProvider>
          <main>
            {children}
          </main>
        </AppProvider>
        <Toaster richColors  />
      </body>
    </html>
  );
}



